language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements_dev.txt"
# command to run tests
script: "nosetests . --with-cover --cover-package=taggart --cover-erase --cover-min-percentage=100"
